# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  pod 'Stripe', '~> 13.2.0'

  

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

